Book.id=3456
Book.title=Let us c
Book.price=300
Book.authors=Kanetkar,Swapna,Amit


Student.sid=456
Student.sname=swapna
Student.course=java


Course.courseId=1
Course.courseName=java
Course.courseCost=50000